package_attributes: ["name", "author", "author_email",
                     "description", "license", "copyright"]

component_attributes: ["name", "package"]

component_interface:
    publisher: ["name"]
    cyclicPublisher: ["name", "frequency"]
    dynParameter: ["name"]
    service: ["name"]
    filter: ["topic_in", "topic_out"]
